spring:
  application:
    name: eureka
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
